#pipeline 
trigger:
- feature/*

pr: none

variables:
  devConnection: 'FreeTrial'
  appName: 'devAppName'

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: build_test
    displayName: 'Build and test'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
      displayName: 'npm install, build, test'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
    - task: PublishPipelineArtifact@0
      inputs:
        targetPath: '$(System.ArtifactsDirectory)'

- stage: deploy
  displayName: 'Deploy app'
  dependsOn: build
  jobs:
  - deployment: deployDev
    displayName: 'Deploy Dev'
    environment: 'TestEnv'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              downloadPath: '$(System.DefaultWorkingDirectory)'
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(devConnection)
              appType: 'webAppLinux'
              appName: $(appName)
              runtimeStack: 'NODE|10.1'
              startUpCommand: 'npm run start'